language: python
sudo: false
python:
    - "3.6"
before_install:
    - pip install numpy
    - pip install pytest>=3.6 pytest-cov
    - pip install coveralls
    - pip install javabridge python-bioformats

script:
    - python setup.py install
    - rm -rf build
    - py.test

after_success:
    - coveralls
